### ISSUE TITLE
I can't make the simulator work

### ISSUE THREAD

**Issue by tuncatunc** [lihbr/prismic-demo-flowrise#1]
Hi thank you for your efforts to bring prismic to vue developer.

I cloned the repo and `npm run dev`, however the simulator can't render ant slice?

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/f48d08c6-6ebc-480a-98e2-3e81ae0eb3fb">

**Comment by lihbr** [comment]
Hi @tuncatunc, you're very welcome! Thanks for trying Prismic ☺️

<details>
<summary>I hate when things are like that, but I have trouble reproducing the issue :/</summary>

![image](https://github.com/user-attachments/assets/4412f7f2-b161-4b44-805c-7b7aef91e90c)

</details>

Here's the process I followed to get this result using **Node 22.0.0 on Windows**:

```bash
git clone git@github.com:lihbr/prismic-demo-flowrise.git
cd prismic-demo-flowrise
npm install
npm run dev
```

- Are you following the same process as above?
- What Node version are you using? Can you ensure it's one of the LTS? (18, 20, or 22 at the time)

Let me know if anything, happy to help :)

**Comment by tuncatunc** [comment]
Thank you , it works with node22

**Comment by lihbr** [comment]
Glad you got it working!
